### PR TITLE
Responsive section34

### PR DESCRIPTION
**Pull request by PNQT**

### CODE REVIEW

**Comment by datmaiz** [comment]
and resolve conflict

**Comment by datmaiz** [comment]
you do not see my comment ?

**Comment by PNQT** [comment]
I just see your cm is resolve conflict

**Comment by datmaiz** [comment]
image

**Comment by PNQT** [comment]
can you make example for me I don't understand it

**Comment by datmaiz** [comment]
use class name and alt attribute clearly. research "alt" attribute for more information.

**Pull request merged**
